Fix: Add ability to auto deploy challenges from remote
sdslabs/beast pull request #287
Opened 2021-07-22 19:35 UTC by techiepriyansh

## Changes
- Added a new flag for the `beast run` command to auto deploy challenges from remote on server start
The flag: `-a, --auto-deploy`

- Modified the existing `-s, --periodic-sync` flag to auto update challenges in addition to just syncing them from remote
## Usage
-  `-a, --auto-deploy`: deploy all challenges from remote on server start
-  `-s, --periodic-sync`: constantly monitor the remote with the `remote_sync_period` defined in the `config.toml` file and look for any changes in the challenges. Then accordingly `deploy`, `redeploy` or `purge` the modified challenges.

Fixes #215

2021-07-23 09:41 UTC, h3llix requested changes

2021-07-23 09:43 UTC, h3llix requested changes

2021-07-26 14:38 UTC, burnerlee reviewed
Just make these minor changes. Rest of it LGTM

2021-07-26 15:47 UTC, ayanchoudhary requested changes

2021-07-29 21:03 UTC, ayanchoudhary approved these changes
LGTM

2021-07-30 16:13 UTC, merged