ShellCheck function written
sdslabs/beast pull request #311
Opened 2021-12-06 13:19 UTC by levihackerman-102

implement Shellcheck

2021-12-18 08:33 UTC, wryonik requested changes

2022-01-03 16:30 UTC, wryonik requested changes

2022-02-17 08:51 UTC, burnerlee reviewed
@levihackerman-102 where have you used the `ShellCheck` function? Or how is it intended to be used?

2022-02-17 08:58 UTC, burnerlee reviewed
@levihackerman-102 where have you used the `ShellCheck` function? Or how is it intended to be used?

2022-06-28 16:37 UTC, closed without merging